cmd/root.go, initializer/initializer.go, initializer/initializer_test.go, senzingconfig/senzingconfig.go, senzingconfig/senzingconfig_test.go, senzingschema/senzingschema.go, senzingschema/senzingschema_test.go
=> #3 Fix cyclo and ineffassign

CHANGELOG.md, Dockerfile, README.md, cmd/root.go, package.Dockerfile
=> Issue 3.dockter.3

.gitignore, CHANGELOG.md, Dockerfile, cmd/root.go, package.Dockerfile
=> Issue 13.dockter.1

CHANGELOG.md, Dockerfile, cmd/root.go, go.mod, go.sum, package.Dockerfile
=> Issue 13.dockter.2

Makefile, cmd/root.go, docs/errors.md, go.mod, go.sum
=> #18 Fix silent exit

CHANGELOG.md, cmd/root.go, go.mod, go.sum
=> Issue 21.dockter.1

CHANGELOG.md, cmd/root.go
=> #28 check for nil return

.github/workflows/go-proxy-pull.yaml, CHANGELOG.md, CONTRIBUTING.md, Dockerfile, Makefile, README.md, cmd/completion.go, cmd/docs.go, cmd/root.go, doc.go, docs/README.md, docs/development.md, docs/errors.md, docs/examples.md, go.mod, initializer/initializer.go, initializer/initializer_test.go, main.go, package.Dockerfile, senzingconfig/senzingconfig.go, senzingconfig/senzingconfig_test.go, senzingschema/senzingschema_test.go
=> Issue 30.dockter.1

.project, README.md, docs/examples.md, go.mod
=> Issue 30.dockter.2

Dockerfile, package.Dockerfile
=> #37 Added equal sign

.github/workflows/dependabot-automation.yaml
=> #97 Add shared dependabot automation workflow

cmd/context_darwin.go, cmd/context_linux.go, cmd/context_windows.go, cmd/root.go, go.mod, go.sum
=> #114 Use new packages

.github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux.yaml, .github/workflows/go-test-windows.yaml, CHANGELOG.md, Makefile, Makefile.darwin, Makefile.linux, Makefile.windows, go.mod, go.sum
=> 168.dockter.1

CHANGELOG.md, Dockerfile, cmd/github.go, rootfs/opt/senzing/g2/resources/templates/g2config.json
=> #223 Prepare for versioned release

.github/workflows/docker-build-container.yaml, .github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml
=> add quiet flag

CHANGELOG.md
=> #344 New release

.github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml
=> update docker push permissions

.github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml, .github/workflows/go-proxy-pull.yaml, .github/workflows/go-test-linux-mssql.yaml, .github/workflows/go-test-linux-mysql.yaml, .github/workflows/go-test-linux-oracle.yaml, .github/workflows/go-test-linux-postgres.yaml, .github/workflows/go-test-linux-sqlite.yaml, .github/workflows/make-go-github-file.yaml, .github/workflows/make-go-tag.yaml
Issue number: senzing-factory/build-resources#179
=> senzing-factory/build-resources#179 add slack notifications

.github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux-mssql.yaml, .github/workflows/go-test-linux-mysql.yaml, .github/workflows/go-test-linux-oracle.yaml, .github/workflows/go-test-linux-postgres.yaml, .github/workflows/go-test-linux-sqlite.yaml, .github/workflows/go-test-windows.yaml
=> #387 nightly cron job for install testing

.github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux-sqlite.yaml, .github/workflows/go-test-windows.yaml
=> remove coverage from slack notifications

.github/workflows/go-test-linux-mssql.yaml, .vscode/cspell.json
=> #415 overwrite existing msft config, remove hardcoded version

.github/workflows/bearer.yaml, .github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux-mssql.yaml, .github/workflows/go-test-linux-mysql.yaml, .github/workflows/go-test-linux-oracle.yaml, .github/workflows/go-test-linux-postgres.yaml, .github/workflows/go-test-linux-sqlite.yaml, .github/workflows/go-test-windows.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/govulncheck.yaml
=> #422 4.0 updates, switch from beta to staging, test prod

.dockerignore, .github/workflows/bearer.yaml, .github/workflows/make-go-tag.yaml, .github/workflows/spellcheck.yaml, Makefile, package.Dockerfile
=> #422 Refactor to template

.github/dependabot.yml, .github/renovate.json, Dockerfile, package.Dockerfile
=> #441 use renovate for docker updates
